name: CI
on: [push, workflow_dispatch]

jobs:
  test:
    name: Run Unit tests
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pod
        run: |
          cd TestObjectiveDropbox
          pod install --repo-update
      - name: Test iOS
        env:
          FULL_DROPBOX_API_APP_KEY: ${{ secrets.FULL_DROPBOX_API_APP_KEY }}
          FULL_DROPBOX_TESTER_TEAM_REFRESH_TOKEN: ${{ secrets.FULL_DROPBOX_TESTER_TEAM_REFRESH_TOKEN }}
          FULL_DROPBOX_TESTER_USER_REFRESH_TOKEN: ${{ secrets.FULL_DROPBOX_TESTER_USER_REFRESH_TOKEN }}
          TEAM_MEMBER_EMAIL: ${{ secrets.TEAM_MEMBER_EMAIL }}
          NON_TEAM_MEMBER_EMAIL: ${{ secrets.NON_TEAM_MEMBER_EMAIL }}
          REFRESH_TOKEN_ACCOUNT_ID: ${{ secrets.REFRESH_TOKEN_ACCOUNT_ID }}
          ANY_OTHER_ACCOUNT_ID: ${{ secrets.ANY_OTHER_ACCOUNT_ID }}
          NON_TEAM_MEMBER_ACCOUNT_ID: ${{ secrets.NON_TEAM_MEMBER_ACCOUNT_ID }}

          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`instruments -s -devices | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
          xcodebuild -workspace TestObjectiveDropbox/TestObjectiveDropbox.xcworkspace/ -scheme TestObjectiveDropbox_iOS -sdk iphonesimulator \
            -destination "platform=$platform,name=$device" \
            FULL_DROPBOX_API_APP_KEY=$FULL_DROPBOX_API_APP_KEY \
            FULL_DROPBOX_TESTER_TEAM_REFRESH_TOKEN=$FULL_DROPBOX_TESTER_TEAM_REFRESH_TOKEN \
            FULL_DROPBOX_TESTER_USER_REFRESH_TOKEN=$FULL_DROPBOX_TESTER_USER_REFRESH_TOKEN \
            TEAM_MEMBER_EMAIL=$TEAM_MEMBER_EMAIL \
            NON_TEAM_MEMBER_EMAIL=$NON_TEAM_MEMBER_EMAIL \
            REFRESH_TOKEN_ACCOUNT_ID=$REFRESH_TOKEN_ACCOUNT_ID \
            ANY_OTHER_ACCOUNT_ID=$ANY_OTHER_ACCOUNT_ID \
            NON_TEAM_MEMBER_ACCOUNT_ID=$NON_TEAM_MEMBER_ACCOUNT_ID \
            test
      - name: Test macOS
        env:
          FULL_DROPBOX_API_APP_KEY: ${{ secrets.FULL_DROPBOX_API_APP_KEY }}
          FULL_DROPBOX_TESTER_TEAM_REFRESH_TOKEN: ${{ secrets.FULL_DROPBOX_TESTER_TEAM_REFRESH_TOKEN }}
          FULL_DROPBOX_TESTER_USER_REFRESH_TOKEN: ${{ secrets.FULL_DROPBOX_TESTER_USER_REFRESH_TOKEN }}
          TEAM_MEMBER_EMAIL: ${{ secrets.TEAM_MEMBER_EMAIL }}
          NON_TEAM_MEMBER_EMAIL: ${{ secrets.NON_TEAM_MEMBER_EMAIL }}
          REFRESH_TOKEN_ACCOUNT_ID: ${{ secrets.REFRESH_TOKEN_ACCOUNT_ID }}
          ANY_OTHER_ACCOUNT_ID: ${{ secrets.ANY_OTHER_ACCOUNT_ID }}
          NON_TEAM_MEMBER_ACCOUNT_ID: ${{ secrets.NON_TEAM_MEMBER_ACCOUNT_ID }}
          platform: ${{ 'macOS' }}
        run: |
          xcodebuild -workspace TestObjectiveDropbox/TestObjectiveDropbox.xcworkspace/ -scheme TestObjectiveDropbox_macOS  \
            -destination "platform=$platform,arch=x86_64" \
            FULL_DROPBOX_API_APP_KEY=$FULL_DROPBOX_API_APP_KEY \
            FULL_DROPBOX_TESTER_TEAM_REFRESH_TOKEN=$FULL_DROPBOX_TESTER_TEAM_REFRESH_TOKEN \
            FULL_DROPBOX_TESTER_USER_REFRESH_TOKEN=$FULL_DROPBOX_TESTER_USER_REFRESH_TOKEN \
            TEAM_MEMBER_EMAIL=$TEAM_MEMBER_EMAIL \
            NON_TEAM_MEMBER_EMAIL=$NON_TEAM_MEMBER_EMAIL \
            REFRESH_TOKEN_ACCOUNT_ID=$REFRESH_TOKEN_ACCOUNT_ID \
            ANY_OTHER_ACCOUNT_ID=$ANY_OTHER_ACCOUNT_ID \
            NON_TEAM_MEMBER_ACCOUNT_ID=$NON_TEAM_MEMBER_ACCOUNT_ID \
            test
